### PR TITLE
fix the fuckin linux.

### PR DESCRIPTION
**Pull request by luigionline1**

### CODE REVIEW

**Review by MemeHoovy — CHANGES_REQUESTED** [review]
how does this fix it exactly?

**Comment by luigionline1** [comment]
ubuntu 20.04 not have somr libs

**Comment by MemeHoovy** [comment]
okay but does flixel work with 22.04 though?

**Comment by luigionline1** [comment]
> okay but does flixel work with 22.04 though? and wouldn't latest be 22.04?

yes flixel works on 22.04 and on workflow ubuntu-latest option uses 20.04 so weirdly

**Review by MemeHoovy — APPROVED** [review]
well okay then

**Comment by mcagabe19** [comment]
ahh finally linux fix

**Review by MemeHoovy — APPROVED** [review]

**Comment by luigionline1** [comment]
@benjaminpants @Erizur can u merge this pull?

**Pull request merged**
